In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix
from sklearn.metrics import precision_score,recall_score,f1_score
from sklearn.model_selection import train_test_split,cross_val_score
import joblib

In [5]:
# load dataset
diseases = pd.read_csv('diseases_classifications.csv')
# data explorrations
print(diseases.isnull().sum())
print(diseases.info())
print(diseases.describe())
print(diseases.columns)

Age                    0
Gender                 0
Fever                  0
Headache               0
Body_Pain              0
Vomiting               0
Weakness               0
Chills                 0
Stomach_Pain           0
Diarrhea               0
Loss_of_Appetite       0
Body_Temperature       0
Unnamed: 12         7625
Duration_Days          0
Diagnosis           4206
dtype: int64
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7625 entries, 0 to 7624
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Age               7625 non-null   int64
 1   Gender            7625 non-null   object
 2   Fever             7625 non-null   object
 3   Headache          7625 non-null   object
 4   Body_Pain         7625 non-null   object
 5   Vomiting          7625 non-null   object
 6   Weakness          7625 non-null   object
 7   Chills            7625 non-null   object
 8   Stomach_Pain      7625 non-null   object
 9   Diarrhea          7625 non-null   object
 10  Loss_of_Appetite  7625 non-null   object
 11  Body_Temperature  7625 non-null   float64
 12  Unnamed: 12       0 non-null      float64
 13  Duration_Days     7625 non-null   int64
 14  Diagnosis         3419 non-null   object
dtypes: float64(2), int64(2), object(11)
memory usage: 893.7+ KB
None
               Age  Body_Temperature  Unnamed: 12  Duration_Days
count  7625.000000       7625.000000          0.0    7625.000000
mean     37.462951         38.896367          NaN       6.725115
std      13.339018          1.453135          NaN       4.261424
min      15.000000         36.000000          NaN       0.000000
25%      26.000000         38.100000          NaN       3.000000
50%      37.000000         39.100000          NaN       6.000000
75%      49.000000         40.100000          NaN      10.000000
max      60.000000         41.000000          NaN      14.000000
Index(['Age', 'Gender', 'Fever', 'Headache', 'Body_Pain', 'Vomiting',
       'Weakness', 'Chills', 'Stomach_Pain', 'Diarrhea', 'Loss_of_Appetite',
       'Body_Temperature', 'Unnamed: 12', 'Duration_Days', 'Diagnosis'],
      dtype='object')

In [6]:
# data cleaning
diseases.duplicated().sum()
diseases.drop_duplicates()
diseases.dropna().sum()

Age                   0
Gender                0
Fever                 0
Headache              0
Body_Pain             0
Vomiting              0
Weakness              0
Chills                0
Stomach_Pain          0
Diarrhea              0
Loss_of_Appetite      0
Body_Temperature    0.0
Unnamed: 12         0.0
Duration_Days         0
Diagnosis             0
dtype: object

In [7]:
# data engineering
diseases.drop(columns=['Unnamed: 12'],inplace=True)

In [8]:
diseases.dropna(subset=['Diagnosis'],inplace=True)
diseases

,Age,Gender,Fever,Headache,Body_Pain,Vomiting,Weakness,Chills,Stomach_Pain,Diarrhea,Loss_of_Appetite,Body_Temperature,Duration_Days,Diagnosis
1,38,Female,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,38.3,13,Typhoid
2,38,Male,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,40.2,11,Typhoid
3,27,Male,Yes,Yes,Yes,Yes,Yes,Yes,No,No,Yes,39.5,3,Malaria
8,25,Male,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,40.9,3,Typhoid
10,34,Female,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,40.0,12,Typhoid
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7615,53,Male,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,Yes,38.4,9,Typhoid
7618,39,Female,Yes,Yes,Yes,No,Yes,Yes,Yes,Yes,Yes,38.7,2,Typhoid
7621,21,Female,Yes,Yes,Yes,Yes,Yes,Yes,No,No,Yes,40.4,4,Malaria
7622,58,Male,Yes,Yes,Yes,No,No,Yes,No,No,Yes,40.5,12,Malaria
7623,40,Male,Yes,Yes,Yes,No,Yes,Yes,No,No,No,38.4,5,Malaria

In [9]:
# encode values 
diseases['Gender'] = diseases['Gender'].map({'Male':1,
                                           'Female':0})

In [10]:
encoder = LabelEncoder()
diseases['Diagnosis'] = encoder.fit_transform(diseases['Diagnosis'])

In [11]:
fever_symptoms = ['Fever',
                  'Headache',
                  'Body_Pain',
                  'Vomiting',
                  'Weakness',
                  'Chills',
                  'Stomach_Pain',
                  'Diarrhea',
                  'Loss_of_Appetite'
]
for fevers in fever_symptoms:
    diseases[fevers] = diseases[fevers].map({'Yes':1,'No':0})

In [12]:
# define features and target
X = diseases.drop(columns=['Diagnosis'])
y = diseases['Diagnosis']

In [13]:
# train test split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [14]:
# create model
model = LogisticRegression(max_iter=1000)
model.fit(X_train,y_train)

LogisticRegression(max_iter=1000)

In [15]:
# make predictions
y_predictions = model.predict(X_test)
print('Predictoins',y_predictions)

Predictoins [2 0 1 0 0 1 1 1 1 1 2 1 0 1 1 2 1 2 1 0 1 1 1 2 2 1 2 1 1 2 1 1 2 2 2 2 2
 2 2 0 2 2 2 2 1 2 1 2 2 0 1 1 2 2 2 2 2 0 2 2 0 2 0 2 1 1 2 1 0 2 2 1 2 2
 2 1 1 1 2 1 2 2 2 2 1 2 2 1 2 1 2 0 2 2 1 1 0 1 0 2 2 2 2 1 2 1 1 2 2 1 0
 2 0 2 2 1 1 2 1 2 2 1 2 1 2 1 2 2 2 1 0 2 2 2 2 1 2 2 2 1 2 2 2 2 2 2 1 2
 2 1 1 2 0 0 2 2 0 1 1 1 2 1 1 2 1 2 1 2 2 2 1 1 0 1 0 0 2 0 1 2 1 2 2 0 2
 2 1 2 0 2 1 1 2 0 2 0 2 0 1 1 0 1 2 2 1 2 2 2 2 2 2 2 2 2 1 2 1 1 0 2 2 1
 2 0 0 2 2 1 2 2 0 2 2 2 2 1 2 2 2 2 0 2 2 2 2 1 1 1 1 2 2 1 2 1 1 2 2 2 0
 1 2 2 2 2 2 0 2 2 1 2 0 1 0 2 2 1 1 0 0 0 1 2 1 2 2 2 2 2 2 2 2 0 1 2 0 1
 1 2 2 2 1 2 2 2 2 2 0 2 1 2 2 2 1 2 1 2 1 0 1 2 2 2 2 2 2 2 2 2 1 2 2 2 1
 2 2 1 2 2 1 1 2 2 1 0 2 0 0 1 2 0 2 2 2 2 1 2 1 2 2 0 1 1 0 1 1 1 1 0 1 2
 2 1 1 1 0 1 2 2 2 2 2 2 0 2 1 0 2 2 2 2 0 1 0 2 1 2 0 2 1 1 2 0 1 2 1 2 1
 2 1 1 1 1 0 2 2 2 2 2 1 2 2 2 1 2 2 0 2 2 2 1 0 2 0 1 2 2 2 2 2 0 2 0 1 2
 2 0 2 2 2 2 0 1 2 2 2 1 2 1 2 2 2 2 2 2 2 1 2 2 1 2 2 2 1 2 2 1 2 1 2 2 2
 0 2 1 2 2 1 2 0 1 1 2 2 0 1 2 0 2 2 1 2 2 1 1 1 2 2 2 2 2 0 0 2 1 1 2 2 1
 2 2 2 2 0 2 2 1 1 0 1 2 0 2 1 2 2 0 2 2 1 2 2 2 2 1 1 2 2 2 2 1 1 1 2 2 1
 2 1 2 2 1 2 1 2 2 1 2 1 2 0 2 2 2 1 1 1 2 2 2 2 1 1 1 1 1 2 2 1 2 2 1 1 0
 0 2 2 2 2 2 2 1 2 2 2 2 2 0 1 2 1 2 0 1 2 2 2 1 1 2 1 0 1 2 2 0 2 0 1 2 2
 1 0 1 2 1 0 2 2 2 2 2 0 0 1 1 2 2 2 1 2 1 1 2 0 2 2 2 0 1 2 2 1 2 2 2 1 2
 0 2 1 2 2 1 2 2 1 0 2 0 2 1 0 2 0 1]

In [16]:
# Model evaluations
accuracy = accuracy_score(y_test,y_predictions)
print('Accuracy Score',accuracy)
precision = precision_score(y_test,y_predictions,average='macro')
print('Precision Score',precision)
recall = recall_score(y_test,y_predictions,average='micro')
print('Recall score',recall)
f1s = f1_score(y_test,y_predictions,average='weighted')
print('F1 Score',f1s)
score_validation = cross_val_score(model, X, y, cv=5)

print("Cross Validation Scores:", score_validation)
print("Average Score:", score_validation.mean())

Accuracy Score 1.0
Precision Score 1.0
Recall score 1.0
F1 Score 1.0
Cross Validation Scores: [1. 1. 1. 1. 1.]
Average Score: 1.0

In [17]:
# confusion matrix
matrix_confusion = confusion_matrix(y_test,y_predictions)
print('Confusion Matrix',matrix_confusion)
# classifications report
print(classification_report(y_test,y_predictions))
# model accuracy
training_accuracy = model.score(X_train,y_train)
print('Training Accuracy',training_accuracy)
testing_accuracy = model.score(X_test,y_test)
print('Testing Accuracy',testing_accuracy)

Confusion Matrix [[ 97   0   0]
 [  0 210   0]
 [  0   0 377]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        97
           1       1.00      1.00      1.00       210
           2       1.00      1.00      1.00       377

    accuracy                           1.00       684
   macro avg       1.00      1.00      1.00       684
weighted avg       1.00      1.00      1.00       684

Training Accuracy 1.0
Testing Accuracy 1.0

In [18]:
# cross valudation score
#score_validation = cross_val_score(X,y,cv=3)
#print('Cross Valdation Score',score_validation)

In [29]:
jo = joblib.dump(model,'diseases_classifications.pkl')
#joblib.dump(encoder,'label_encoder.pkl')
print(jo)

['diseases_classifications.pkl']

In [20]:
# new patients data
patients = pd.DataFrame({
    'Age':[25],
    'Gender':['Male'],
    'Fever':['Yes'],
    'Headache':['Yes'],
    'Body_Pain':['Yes'],
    'Vomiting':['No'],
    'Weakness':['Yes'],
    'Chills':['Yes'],
    'Stomach_Pain':['No'],
    'Diarrhea':['No'],
    'Loss_of_Appetite':['Yes'],
    'Body_Temperature':[39.5],
    'Duration_Days':[4]
})

# ==========================================
# ENCODE GENDER
# ==========================================

patients['Gender'] = (
    patients['Gender']
    .astype(str)
    .str.strip()
    .str.capitalize()
    .map({
        'Male': 0,
        'Female': 1
    })
)

# ==========================================
# ENCODE YES / NO FEATURES
# ==========================================

yes_no_columns = [
    'Fever',
    'Headache',
    'Body_Pain',
    'Vomiting',
    'Weakness',
    'Chills',
    'Stomach_Pain',
    'Diarrhea',
    'Loss_of_Appetite'
]

for col in yes_no_columns:
    patients[col] = (
        patients[col]
        .astype(str)
        .str.strip()
        .str.capitalize()
        .map({
            'Yes': 1,
            'No': 0
        })
    )

# ==========================================
# MATCH TRAINING COLUMN ORDER
# ==========================================

patients = patients[X_train.columns]
    
    
prediction = model.predict(patients)

print(encoder.inverse_transform(prediction)[0])
prediction = model.predict(patients)

predicted_disease = encoder.inverse_transform(prediction)

print("="*50)
print("Disease Prediction Result")
print("="*50)
print("Predicted Disease:", predicted_disease[0])
print("="*50)
probability = model.predict_proba(patients)

print("\nPrediction Probability")

for disease, prob in zip(encoder.classes_, probability[0]):
    print(f"{disease}: {prob*100:.2f}%")

Malaria
==================================================
Disease Prediction Result
==================================================
Predicted Disease: Malaria
==================================================

Prediction Probability
Both: 0.01%
Malaria: 99.63%
Typhoid: 0.37%

In [21]:
# match training columns
patients = patients[X_train.columns]
patients

,Age,Gender,Fever,Headache,Body_Pain,Vomiting,Weakness,Chills,Stomach_Pain,Diarrhea,Loss_of_Appetite,Body_Temperature,Duration_Days
0,25,0,1,1,1,0,1,1,0,0,1,39.5,4

In [22]:
print(model.classes_)
print(encoder.classes_)

[0 1 2]
['Both' 'Malaria' 'Typhoid']

In [23]:
print("Disease Prediction Result")
print('Predicted Diseases:',patients)

Disease Prediction Result
Predicted Diseases:    Age  Gender  Fever  Headache  Body_Pain  Vomiting  Weakness  Chills  \
0   25       0      1         1          1         0         1       1

   Stomach_Pain  Diarrhea  Loss_of_Appetite  Body_Temperature  Duration_Days
0             0         0                 1              39.5              4

In [24]:
print(model.classes_)

[0 1 2]